{
  "hash": "5574a957b2ac861c25217d67e33c01b2",
  "result": {
    "engine": "knitr",
    "markdown": "# Visualizing data distributions {#sec-dataviz-distributions}\n\nSummarizing complex datasets is crucial in data analysis, allowing us to share insights drawn from the data more effectively. One common method is to use the *average* value to summarize a list of numbers. For instance, a high school's quality might be represented by the average score in a standardized test. Sometimes, an additional value, the *standard deviation*, is added. So, a report might say the scores were 680 $\\pm$ 50, boiling down a full set of scores to just two numbers. But is this enough? Are we overlooking crucial information by relying solely on these summaries instead of the complete data?\n\nOur first data visualization building block is learning to summarize lists of numbers or categories. More often than not, the best way to share or explore these summaries is through data visualization. The most basic statistical summary of a list of objects or numbers is its distribution. Once a data has been summarized as a distribution, there are several data visualization techniques to effectively relay this information. For this reason, it is important to have a deep understand of the concept of a distribution.\n\nIn this chapter, we discuss properties of a variety of distributions and how to visualize distributions using a motivating example of participant reaction times.\n\n## Variable types\n\nThe two main variables types are *categorical* and *numeric*. Each can be divided into two other groups: categorical can be ordinal or not, whereas numerical variables can be discrete or continuous. When entry in a dataset represent a group rather than a number w we refer to the data as *categorical data*. Two simple examples are sex (male or female) and US regions (Northeast, South, North Central, West). Some categorical data can be ordered even if they are not numbers per se, such as spiciness (mild, medium, hot). In statistics, ordered categorical data are referred to as *ordinal* data. Examples of numerical data are active-user counts, data-breach incident rates, and reaction times. We can further divide numerical data into continuous and discrete. Continuous variables are those that can take any value, such as reaction times, if measured with enough precision. For example, two participants completing the same trial may respond in 342.12 and 342.11 milliseconds, respectively. Counts, such as active-user counts, are discrete because they have to be round numbers.\n\nKeep in mind that discrete numeric data can be considered ordinal. Although this is technically true, we usually reserve the term ordinal data for variables belonging to a small number of different groups, with each group having many members. In contrast, when we have many groups with few cases in each group, we typically refer to them as discrete numerical variables. So, for example, the number of packs of cigarettes a person smokes a day, rounded to the closest pack, would be considered ordinal, while the actual number of cigarettes would be considered a numerical variable. But, indeed, there are examples that can be considered both numerical and ordinal when it comes to visualizing data.\n\nHere we focus on numeric variables because visualizing this data type is substantially more complex. However, we start by describing data visualization and summarization approaches for categorical data.\n\n## Case study: describing reaction times\n\nWe introduce a new motivating problem. It is an artificial one, but it will help us illustrate the concepts needed to understand distributions.\n\nPretend that we have to describe the reaction times of our study participants to ET, an extraterrestrial that has never run a psychology experiment. As a first step, we need to collect data. To do this, we ask participants to complete a simple reaction-time task and record their response time in milliseconds. We ask them to provide sex information because we know there are two different reaction-time distributions by sex. We collect the data and save it in the `reaction_times` data frame:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(behdslabs)\nhead(reaction_times)\n#>      sex rt_ms\n#> 1   Male   430\n#> 2   Male   384\n#> 3   Male   365\n#> 4   Male   420\n#> 5   Male   301\n#> 6 Female   338\n```\n:::\n\n\nOne way to convey the reaction times to ET is to simply send them this list of 1,050 reaction times. But there are much more effective ways to convey this information, and understanding the concept of a distribution will be key. To simplify the explanation, we first focus on male reaction times. We examine the female reaction-time data in @sec-student-height-cont.\n\n## Distributions\n\nThe most basic statistical summary of a list of objects or numbers is its *distribution*. The simplest way to think of a distribution is as a compact description of a list with many entries. This concept should not be new for readers of this book. For example, with categorical data, the distribution simply describes the proportion of each unique category. The sex represented in the `reaction_times` dataset is:\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> \n#> Female   Male \n#>  0.227  0.773\n```\n:::\n\n\nThis two-category *frequency table* is the simplest form of a distribution. We don't really need to visualize it since one number describes everything we need to know: 23% are females and the rest are males. When there are more categories, then a simple barplot describes the distribution. Here is an example with US state regions:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/state-region-distribution-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nThis particular plot simply shows us four numbers, one for each category. We usually use barplots to display a few numbers. Although this particular plot does not provide much more insight than a frequency table itself, it is a first example of how we convert a vector into a plot that succinctly summarizes all the information in the vector. When the data is numerical, the task of displaying distributions is more challenging.\n\n### Histograms\n\nNumerical data that are not categorical also have distributions. However, in general, when data is not categorical, reporting the frequency of each entry, as we did for categorical data, is not an effective summary since most entries are unique. For example, in our case study, while several participants recorded a reaction time close to 374 milliseconds, only one participant recorded a reaction time of `283.1325` milliseconds and only one recorded a reaction time of `435.0265` milliseconds. This level of precision is typical of computer-timed reaction-time tasks, which log responses to a fraction of a millisecond.\n\nStatistics textbooks teach us that a more useful way to define a distribution for numeric data is to define a function that reports the proportion of the data below $a$ for all possible values of $a$. This function is called the empirical cumulative distribution function (eCDF), it can be plotted, and it provides a full description of the distribution of our data. Here is the eCDF for male reaction times:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/ecdf-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nHowever, summarizing data by plotting the eCDF is actually not very popular in practice. The main reason is that it does not easily convey characteristics of interest such as: at what value is the distribution centered? Is the distribution symmetric? What ranges contain 95% of the values?\n\n*Histograms* are much preferred because they greatly facilitate answering such questions. Histograms sacrifice just a bit of information to produce plots that are much easier to interpret. The simplest way to make a histogram is to divide the span of our data into non-overlapping bins of the same size. Then, for each bin, we count the number of values that fall in that interval. The histogram plots these counts as bars with the base of the bar defined by the intervals. Here is the histogram for the reaction-time data splitting the range of values into ten-millisecond intervals: $(195, 205]$, $(205, 215]$, $(215,225]$, $(225,235]$, $...$, $(495,505]$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/rt-histogram-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nAs you can see in the figure above, a histogram is similar to a barplot, but it differs in that the x-axis is numerical, not categorical.\n\nIf we send this plot to ET, they will immediately learn some important properties about our data. First, the range of the data is from 200 to 500 with the majority (more than 95%) between 305 and 439 milliseconds. Second, the reaction times are close to symmetric around 377 milliseconds. Also, by adding up counts, ET could obtain a very good approximation of the proportion of the data in any interval. Therefore, the histogram above is not only easy to interpret, but also provides almost all the information contained in the raw list of 812 male reaction times with about 30 bins.\n\nWhat information do we lose? Note that all values in each interval are treated the same when computing bin heights. So, for example, the histogram does not distinguish between 340, 340.1, and 340.2 milliseconds. Given that these differences are almost unnoticeable to the eye, the practical implications are negligible and we were able to summarize the data to just 26 numbers.\n\nWe discuss how to code histograms in @sec-other-geometries.\n\n### Smoothed density\n\n*Smooth density* plots relay the same information as a histogram but are aesthetically more appealing. Here is what a smooth density plot looks like for our male reaction-time data:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/example-of-smoothed-density-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nIn this plot, we no longer have sharp edges at the interval boundaries and many of the local peaks have been removed. Also, the scale of the y-axis changed from counts to *density*. To fully understand smooth densities, we have to understand *estimates*, a topic covered in statistics our advanced data science textbooks. Here we simply describe them as making the histograms prettier by drawing a curve that goes through the top of the histogram bars and then removing the bars. The values shown y-axis are chosen so that the area under the curve adds up to 1. This implies that for any interval, the area under the curve for that interval gives us an approximation of how what proportion of the data is in the interval.\n\nAn advantage of smooth densities over histograms for visualization purposes is that densities make it easier to compare two distributions. This is in large part because the jagged edges of the histogram add clutter. Here is an example comparing male and female reaction times:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/two-densities-one-plot-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nWith the right argument, `ggplot` automatically shades the intersecting region with a different color. We will show examples of **ggplot2** code for densities in @sec-dataviz-in-practice as well as @sec-other-geometries.\n\n### The normal distribution {#sec-dataviz-normal-distribution}\n\nHistograms and density plots provide excellent summaries of a distribution. But can we summarize even further? We often see the average and standard deviation used as summary statistics: a two-number summary! To understand what these summaries are and why they are so widely used, we need to understand the normal distribution.\n\nThe normal distribution, also known as the bell curve and as the Gaussian distribution. Here is what the normal distribution looks like:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/normal-distribution-density-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nThe normal distribution is one of the most famous mathematical concepts in history. A reason for this is that the distribution of many datasets can be approximated with normal distributions. These include gambling winnings, reaction times, weights, blood pressure, standardized test scores, and experimental measurement errors. Statistical textbooks offer explanations for why this is the case. But how can the same distribution approximate datasets with completely different ranges for values, for example reaction times and weights? A second important characteristic of the normal distribution is that it can be adapted to different datasets by just adjusting two numbers, referred to as the *average* or *mean* and the *standard deviation* (SD). The normal distribution is symmetric, centered at what we refer to as the average, and most values (about 95%) are within 2 SDs from the average. The plot above shows a normal distribution with average 0 and SD 1, often referred to as a *standard normal*. Note that the fact that only two numbers are needed to adapt the normal distribution to a dataset implies that if our data distribution is approximated by a normal distribution, all the information needed to describe the distribution can be encoded by just two numbers. We now define these values for an arbitrary list of numbers.\n\nOnce we are convinced that our data, say it is stored in the vector `x`, has a distribution that is *approximately normal*, we can find the specific one that matches our data by matching the average and SD of the data to the average and SD of the normal distribution, respectively. For a list of numbers contained in a vector `x`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nindex <- reaction_times$sex == \"Male\"\nx <- reaction_times$rt_ms[index]\n```\n:::\n\n\nthe average is defined as\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm <- sum(x) / length(x)\n```\n:::\n\n\nand the SD is defined as\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ns <- sqrt(sum((x - m)^2) / length(x))\n```\n:::\n\n\nwhich can be interpreted as the average distance between values and their average.\n\nThe pre-built functions `mean` and `sd` (note that, for reasons explained in statistics textbooks,`sd` divides by `length(x)-1` rather than `length(x)`) can be used here:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm <- mean(x)\ns <- sd(x)\nc(average = m, sd = s)\n#> average      sd \n#>   377.3    33.2\n```\n:::\n\n\nHere is a plot of our reaction-time smooth density in blue and the normal distribution with mean = 377.3 and SD = 33.2 plotted as a black line:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/data-and-normal-densities-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Boxplots {#sec-boxplots}\n\nTo understand boxplots we need to define some terms that are commonly used in exploratory data analysis.\n\nThe *percentiles* are the values for which $p = 0.01, 0.02, ..., 0.99$ of the data are less then or equal to that value, respectively. We call, for example, the case of $p=0.10$ the 10th percentile, which gives us a number for which 10% of the data is below. The most famous percentile is the 50th, also known as the *median*. Another special case that receives a name are the *quartiles*, which are obtained when setting $p=0.25,0.50$, and $0.75$, which are used by the boxplot.\n\nTo motivate boxplots we will go back to the data-breach incident data. Suppose we want to summarize the breach-rate distribution. Using the data visualization technique we have learned, we can quickly see that the normal approximation does not apply here:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/hist-non-normal-data-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nIn this case, the histogram above or a smooth density plot would serve as a relatively succinct summary.\n\nNow suppose those used to receiving just two numbers as summaries ask us for a more compact numerical summary.\n\nThe *boxplot* provides a five-number summary composed of the range (the minimum and maximum) along with the *quartiles* (the 25th, 50th, and 75th percentiles). The R implementation of boxplots ignore *outliers* when computing the range and instead plot these as independent points. The help file provides a specific definition of outliers. The boxplot shows these numbers as a \"box\" with \"whiskers\"\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/first-boxplot-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nwith the box defined by the 25% and 75% percentile and the whiskers showing the range. The distance between the 25% and 75% percentile is called the *interquartile* range. The two points are outliers according to the R implementation. The median is shown with a horizontal line.\n\nFrom just this simple plot, we know that the median is about 2.7, that the distribution is not symmetric, and that the range is 0 to 5 for the great majority of states with two exceptions.\n\nWe discuss how to make boxplots in @sec-other-geometries.\n\n## Stratification {#sec-dataviz-stratification}\n\nIn data analysis we often divide observations into groups based on the values of one or more variables associated with those observations. For example in the next section we divide the reaction-time values into groups based on a sex variable: females and males. We call this procedure *stratification* and refer to the resulting groups as *strata*.\n\nStratification is common in data visualization because we are often interested in how the distributions of variables differ across different subgroups. We will see several examples throughout this part of the book, starting with the next section.\n\n## Case study continued {#sec-student-height-cont}\n\nIf we are convinced that the male reaction-time data is well approximated with a normal distribution we can report back to ET a very succinct summary: male reaction times follow a normal distribution with an average of 377.3 milliseconds and a SD of 33.2 milliseconds. With this information, ET will have a good idea of what to expect when they test our male participants. However, to provide a complete picture we need to also provide a summary of the female reaction times.\n\nBoxplots are useful when we want to quickly compare two or more distributions. Here are the reaction times for men and women:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/female-male-boxplots-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nThe plot immediately reveals that males are, on average, slower to respond than females. The interquartile ranges appear to be similar. But does the normal approximation also work for the female reaction-time data collected by the study? We expect that they will follow a normal distribution, just like males. However, exploratory plots reveal that the approximation is not as useful:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/histogram-qqplot-female-reaction-times-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nWe see something we did not see for the males: the density plot has a second \"bump\". When reporting back to ET, we might need to provide a histogram rather than just the average and standard deviation for the female reaction times.\n\nHowever, go back and read Tukey's quote. We have noticed what we didn't expect to see. If we look at other female reaction-time distributions, we do find that they are well approximated with a normal distribution. So why are our female participants different? Is our sample partly drawn from a group of competitive gamers with unusually fast reflexes? Are a small proportion of female participants actually male participants who were assigned the wrong sex label? Another, perhaps more likely, explanation is that in the data-entry form participants used, `FEMALE` was the default sex and some male participants completed the task but forgot to change the sex field. In any case, data visualization has helped discover a potential flaw in our data.\n\nRegarding the five smallest values, note that these values are:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nreaction_times |> filter(sex == \"Female\") |>\n  slice_min(rt_ms, n = 5) |>\n  pull(rt_ms)\n#> [1] 209 218 218 228 246\n```\n:::\n\n\nBecause genuine visual reaction time rarely drops below about 200 milliseconds, a possibility is that these were anticipatory presses: participants responding before the stimulus appeared, rather than truly reacting to it.\n\n## Exercises\n\n1\\. Define variables containing the reaction times of males and females like this:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(behdslabs)\nmale <- reaction_times$rt_ms[reaction_times$sex == \"Male\"]\nfemale <- reaction_times$rt_ms[reaction_times$sex == \"Female\"]\n```\n:::\n\n\nHow many measurements do we have for each?\n\n2\\. Suppose we can't make a plot and want to compare the distributions side by side. We can't just list all the numbers. Instead, we will look at the percentiles. In @sec-boxplots we defined percentiles as the values for which $p = 0.01, 0.02, \\ldots, 0.99$ of the data are less than or equal to that value. The `quantile` function, which we used in @sec-tidyverse and @sec-data.table, is a generalization: `quantile(x, p)` returns the value for which proportion `p` of the data in `x` are at or below, for any `p` between 0 and 1. Percentiles are the special case where $p$ is one of $0.01, 0.02, \\ldots, 0.99$, for example, `quantile(x, 0.10)` gives the 10th percentile. You can pass a vector of proportions to get several percentiles at once:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nquantile(male, c(0.10, 0.30, 0.50, 0.70, 0.90))\n```\n:::\n\n\nUse this to create a five-element vector `female_percentiles` and a five-element vector `male_percentiles` containing the 10th, 30th, 50th, 70th, and 90th percentiles for each sex. Then create a data frame with these two vectors as columns.\n\n3\\. Study the following boxplots showing active-user-base sizes by country:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](distributions_files/figure-html/boxplot-exercise-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nWhich continent has the country with the biggest active-user base?\n\n4\\. What continent has the largest median active-user base?\n\n5\\. What is the median active-user base for Africa, to the nearest million?\n\n6\\. What proportion of countries in Europe have an active-user base below 14 million?\n\na.  0.99\nb.  0.75\nc.  0.50\nd.  0.25\n\n7\\. If we use a log transformation, which continent shown above has the largest interquartile range?\n\n8\\. Load the reaction-time data set and create a vector `x` with just the male reaction times:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(behdslabs)\nx <- reaction_times$rt_ms[reaction_times$sex==\"Male\"]\n```\n:::\n\n\nWhat proportion of the data is between 375 and 400 milliseconds (more than 375, but no more than 400 milliseconds)? Hint: use a logical operator and `mean`.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}